workflows:
  react-native-app:
    name: React Native App
    max_build_duration: 60
    environment:
      node: 18
      npm: true
      android: true
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Fix Gradle permissions
        script: chmod +x android/gradlew
      - name: Build Android debug
        script: cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - you@example.com
        notify:
          success: true
          failure: true
