workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 16
        JAVA_VERSION: 11
      node: $NODE_VERSION
      java: $JAVA_VERSION
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Start Metro bundler (for JS bundle)
        script: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res
      - name: Build Android debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - narcida03@gmail.com
