workflows:
  react-native-app:
    name: React Native ARILAC-AI-AA
    max_build_duration: 60
    environment:
      node: latest
      java: 17
    scripts:
      - name: Install deps
        script: npm install
      - name: Android build
        script: |
          cd android && ./gradlew assembleDebug
      - name: iOS build
        script: |
          cd ios && pod install --repo-update
          xcodebuild -workspace arilac_ai_aa.xcworkspace -scheme arilac_ai_aa -sdk iphonesimulator -configuration Debug build
    artifacts:
      - android/app/build/outputs/**/*.apk
      - ios/build/**/*.app
    publishing:
      email:
        recipients:
          - you@example.com
        notify:
          success: true
          failure: true
