workflows:
  android-build:
    name: Android Debug Build
    environment:
      node: 16
      java: 11
    scripts:
      - name: Install dependencies
        script: npm install

      - name: Ensure Android assets directory exists
        script: mkdir -p android/app/src/main/assets

      - name: Bundle JS for Android
        script: npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

      - name: Build Android debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
